# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./

# Use npm ci if package-lock.json exists
RUN npm install --ignore-scripts

# Bundle app source
COPY . .

# Build the project
RUN npm run build

# Expose port if necessary (assuming the server listens on a port, if not, remove it)
# EXPOSE 3000

# Run the server
CMD ["node", "dist/server.js"]
